updater script:
  code URL: https://github.com/NeomindLabs/neomind-dashboard

Leftronic dashboard:
  dashboard access key: 'bGVmdHJvbmljaXNhd2Vz' # find on https://www.leftronic.com/api/
  stream names:
  
    statuses for CI project names:
      "Project Alpha": project_alpha_ci_status
      "Project Beta": project_beta_ci_status
      "Project Gamma": project_gamma_ci_status
    
    daily logged hours: freckle_daily_hours
    
    updater script:
      # define these if using a SinglePartDashboardUpdater
      # status spotlight: updater_script_status_spotlight
      # status text: updater_script_status_text
      
      # if using a MultiPartDashboardUpdater
      statuses for part IDs:
        "hours": updater_script_hours_status_text
        "build_status": updater_script_build_status_status_text

BigTuna CI:
  statuses URL: http://bigtuna.example.com/projects # URL for BigTuna page with list of projects

Freckle:
  account host: apitest # xxx.letsfreckle.com
  username: apitest@letsfreckle.com # the email you sign in with
  token: 'lx3gi6pxdjtjn57afp8c2bv1me7g89j' # get this from Settings & Tools > API
